themeName = "Plain-SeKai"

[default]
header = "template/header/header.toml"
footer = "template/footer/footer.toml"
mask = "template/mask/mask.toml"

[Entrance]
EntrancesMap = [
    "pages/login/entrance.toml : /user/login",
]

[static]
staticMap = [
    "template/header/stylesheets/styles.css : backStage/stylesheets/styles.css",
    "pages/login/header/stylesheets/styles.css : user/stylesheets/styles.css"
]