themeName = "Plain-SeKai"

[default]
header = "template/header/header.toml"
footer = "template/footer/footer.toml"
mask = "template/mask/mask.toml"

[Entrance]
EntrancesMap = [
    "pages/user/login/entrance.toml :: /backStage/user/login",
    "pages/post/create/entrance.toml :: /backStage/post/create",
    "pages/user/edit/entrance.toml :: /backStage/user/edit",
    "pages/framework/entrance.toml :: /backStage/",
]

[static]
staticMap = [
#    template header static
    "template/header/stylesheets/styles.css :: /backStage/stylesheets/styles.css",
    "template/header/scripts/function.js :: /backStage/scripts/function.js",
    "template/header/scripts/styles.js :: /backStage/scripts/styles.js",
#    login static
    "pages/user/login/header/stylesheets/styles.css :: /backStage/user/login/stylesheets/styles.css",
#    framework static
    "pages/framework/header/stylesheets/styles.css :: /backStage/framework/stylesheets/styles.css",
#    postEdit static
    "pages/post/create/header/stylesheets/styles.css :: /backStage/post/create/stylesheets/styles.css",
#    userEdit static
    "pages/user/edit/header/stylesheets/styles.css :: /backStage/user/edit/stylesheets/styles.css",

]