themeName = "Plain-SeKai"

[default]
header = "template/header/header.tmpl"
footer = "template/footer/footer.tmpl"
mask = "template/mask/mask.tmpl"

[pages]
pagesMap = [
    "pages/login/login.toml : /user/login",
]

[static]
staticMap = [
    "template/header/stylesheets/styles.css : backStage/stylesheets/styles.css",
    "pages/login/header/stylesheets/styles.css : user/stylesheets/styles.css"
]