version = "0.0.1"
language = "zh_cn"

[http]
port = 12070

[log]
dir = "./logs"

[database]
type = "sqlite3"

[database.sqlite3]
dir = "./database.sql"

[database.mysql]
server = "localhost"
port = 3306
username = "sekai"
password = "7355608"
db = "sekai"