version = '0.0.1'
language = 'zh_cn'

[http]
port = 12070

[log]
dir = './logs'

[database]
type = 'sqlite3'

[database.sqlite3]
dir = './sekai.db'

[database.mysql]
server = 'localhost'
port = 3306
username = ''
password = ''
db = ''

[siteConfig]
siteRoot = 'localhost:12070'
siteHome = 'localhost:12070'
siteName = 'SeKai'
siteDescription = 'powered by Golang'
siteBackStageTheme = 'Plain-SeKai'
siteFrontStageTheme = 'Plain-SeKai'

[googleAuth]
salt = "sekais"