version = '0.0.1'
language = 'zh_cn'

[http]
port = 12070

[log]
dir = './logs'

[database]
type = 'sqlite3'

[database.sqlite3]
dir = './sekai.db'

[database.mysql]
server = 'localhost'
port = 3306
username = ''
password = ''
db = ''

[siteConfig]
siteUrl = 'http://localhost:12070'
siteHome = 'http://localhost:12070'
siteName = 'Sekai'
siteDescription = 'powered by Golang'
siteTheme = 'plain-sekai'
