themeName = "Plain-SeKai"

[default]
header = "template/header/header.toml"
footer = "template/footer/footer.toml"
mask = "template/mask/mask.toml"

[Entrance]
EntrancesMap = [
    "pages/home/entrance.toml : /",
]

[static]
staticMap = [
    "template/header/stylesheets/styles.css : stylesheets/styles.css",
#    "pages/login/header/stylesheets/styles.css : user/stylesheets/styles.css"
]