language="zh_cn"

[serverLogger]
loadConfigMessage = "加载配置文件与记录器成功"
httpStartingMessage = "现在启动HTTP服务器..."
httpStartingError = "HTTP服务器开启失败"
httpServerShutdownMessage = "服务器关闭中..."
httpServerShutdownError = "服务器关闭失败"
httpServerExited = "服务器已关闭"
chunkTemplateLoadedError = "chunk.tmpl 加载失败"
loadPageError = "读取Page错误"
tomlUnmarshalError = "toml解析错误"
readFileError = "读取文件错误"
sameThemeExist = "主题存在同名"
inlineFileReadError = "内部文件读取错误"